components:
  schemas:
    TemperatureSensor:
      type: object
      required:
        -  temperature
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing temperature`.
      
      properties:
        temperature:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    ConductivitySensor:
      type: object
      required:
        -  conductitivity
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing conductivity`.
      
      properties:
        conductitivity:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    ChlorophyllSensor:
      type: object
      required:
        -  chlorophyll
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing chlorophyll`.
      
      properties:
        chlorophyll:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    HumiditySensor:
      type: object
      required:
        -  humidity
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing humidity`.
      
      properties:
        humidity:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    OrganicMatterSensor:
      type: object
      required:
        -  organicMatter
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing organicMatter`.
      
      properties:
        organicMatter:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    OxygenSensor:
      type: object
      required:
        -  oxygen
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing oxygen`.
      
      properties:
        oxygen:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    PhSensor:
      type: object
      required:
        -  pH
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing pH`.

      properties:
        pH:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    PiezometricLevelSensor:
      type: object
      required:
        -  piezometricLevel
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing piezometricLevel`.
      
      properties:
        piezometricLevel:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    PolyethyleneSensor:
      type: object
      required:
        -  polyethylene
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing polyethylene`.
      
      properties:
        polyethylene:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    PrecipitationSensor:
      type: object
      required:
        -  precipitation
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing precipitation`.
      
      properties:
        precipitation:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    PressureSensor:
      type: object
      required:
        -  pressure
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing pressure`.
      
      properties:
        pressure:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    SalinitySensor:
      type: object
      required:
        -  salinity
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of salinity`.
      
      properties:
        salinity:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    TdsSensor:
      type: object
      required:
        -  tds
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used to measure the total amount of mobile charged ions, including minerals, salts or metals dissolved in a given volume of water, expressed in units of mg per unit volume of water (mg/L), also referred to as parts per million (ppm).
      
      properties:
        tds:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    TransparencySensor:
      type: object
      required:
        -  transparency
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used to measure the transparency of the water.
      
      properties:
        transparency:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    TurbiditySensor:
      type: object
      required:
        -  turbidity
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used to measure the turbidity of the water.
      
      properties:
        turbidity:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    VolumeSensor:
      type: object
      required:
        -  volume
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and is used to measure the volume of the water.
      
      properties:
        volume:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    WaterFlowSensor:
      type: object
      required:
        -  waterFlow
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category `Sensor` and measures the flow of water.
      
      properties:
        waterFlow:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
    WaterLevelSensor:
      type: object
      required:
        -  waterLevel
      allOf:
        - $ref: 'file:/home/mario/tutorials.Understanding-At-Context/device.yaml'

      description: >
        A device that consists of a sensor, has category Sensor and is used to measure the level of the water.
      
      properties:
        waterLevel:
          $ref: 'file:/home/mario/tutorials.Understanding-At-Context/properties-saref.yaml'
info: 
  description: "Model Definition for Mar Menor enviroment"
  title: Smart Devices Mar Menor Data Models
  version: "1.0.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object