components:
  schemas:
    TemperatureSensor:
      type: object
      required:
        -  temperature
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing temperature`.
      
      properties:
        temperature:
          $ref: ./genericProperties.yaml#/temperature
    ConductivitySensor:
      type: object
      required:
        -  conductivity
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing conductivity`.
      
      properties:
        conductivity:
          $ref: ./genericProperties.yaml#/conductivity
    ChlorophyllSensor:
      type: object
      required:
        -  chlorophyll
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing chlorophyll`.
      
      properties:
        chlorophyll:
          $ref: ./genericProperties.yaml#/chlorophyll
    HumiditySensor:
      type: object
      required:
        -  humidity
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing humidity`.
      
      properties:
        humidity:
          $ref: ./genericProperties.yaml#/humidity
    OrganicMatterSensor:
      type: object
      required:
        -  organicMatter
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing organicMatter`.
      
      properties:
        organicMatter:
          $ref: ./genericProperties.yaml#/organicMatter
    OxygenSensor:
      type: object
      required:
        -  oxygen
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing oxygen`.
      
      properties:
        oxygen:
          $ref: ./genericProperties.yaml#/oxygen
    PhSensor:
      type: object
      required:
        -  pH
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing pH`.

      properties:
        pH:
          $ref: ./genericProperties.yaml#/pH
    PiezometricLevelSensor:
      type: object
      required:
        -  piezometricLevel
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing piezometricLevel`.
      
      properties:
        piezometricLevel:
          $ref: ./genericProperties.yaml#/piezometricLevel
    PolyethyleneSensor:
      type: object
      required:
        -  polyethylene
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing polyethylene`.
      
      properties:
        polyethylene:
          $ref: ./genericProperties.yaml#/polyethylene
    PrecipitationSensor:
      type: object
      required:
        -  precipitation
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing precipitation`.
      
      properties:
        precipitation:
          $ref: ./genericProperties.yaml#/precipitation
    PressureSensor:
      type: object
      required:
        -  pressure
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of sensing pressure`.
      
      properties:
        pressure:
          $ref: ./genericProperties.yaml#/pressure
    SalinitySensor:
      type: object
      required:
        -  salinity
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used for the purpose of salinity`.
      
      properties:
        salinity:
          $ref: ./genericProperties.yaml#/salinity
    TdsSensor:
      type: object
      required:
        -  tds
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used to measure the total amount of mobile charged ions, including minerals, salts or metals dissolved in a given volume of water, expressed in units of mg per unit volume of water (mg/L), also referred to as parts per million (ppm).
      
      properties:
        tds:
          $ref: ./genericProperties.yaml#/tds
    TransparencySensor:
      type: object
      required:
        -  transparency
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used to measure the transparency of the water.
      
      properties:
        transparency:
          $ref: ./genericProperties.yaml#/transparency
    TurbiditySensor:
      type: object
      required:
        -  turbidity
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used to measure the turbidity of the water.
      
      properties:
        turbidity:
          $ref: ./genericProperties.yaml#/turbidity  
    VolumeSensor:
      type: object
      required:
        -  volume
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and is used to measure the volume of the water.
      
      properties:
        volume:
          $ref: ./genericProperties.yaml#/volume
    WaterFlowSensor:
      type: object
      required:
        -  waterFlow
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category `Sensor` and measures the flow of water.
      
      properties:
        waterFlow:
          $ref: ./genericProperties.yaml#/flow
    WaterLevelSensor:
      type: object
      required:
        -  waterLevel
      allOf:
        - $ref: ./sensorDevice.yaml#/SensorDevice

      description: >
        A device that consists of a sensor, has category Sensor and is used to measure the level of the water.
      
      properties:
        waterLevel:
          $ref: ./genericProperties.yaml#/waterLevel
    Buoy:
      type: object
      allOf:
        - $ref: ./buoy.yaml#/Buoy
      x-ngsi:
        uri-prefix: https://raw.githubusercontent.com/mariete1223/MarMenor/main/Buoy/buoy.yaml
    Ravine:
      type: object
      allOf:
        - $ref: ./ravine.yaml#/Ravine
      x-ngsi:
        uri-prefix: https://raw.githubusercontent.com/mariete1223/MarMenor/main/Ravine/ravine.yaml
    PiezometricPoint:
      type: object
      allOf:
        - $ref: ./piezometricPoint.yaml#/PiezometricPoint
      x-ngsi:
        uri-prefix: https://raw.githubusercontent.com/mariete1223/MarMenor/main/PiezometricPoint/piezometricPoint.yaml
info: 
  description: "Model Definition for Mar Menor enviroment"
  title: Smart Devices Mar Menor Data Models
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object