components:
  schemas:
    Device:
      type: object
      allOf:
        - $ref: https://raw.githubusercontent.com/smart-data-models/dataModel.Device/master/Device/model.yaml#/Device

      properties:
        controlledProperty:
          description: 'Anything that can be sensed, measured or controlled by.'
          items:
            enum:
              - airPollution
              - atmosphericPressure
              - averageVelocity
              - batteryLife
              - batterySupply
              - cdom
              - conductance
              - conductivity
              - chlorophyll
              - depth
              - eatingActivity
              - electricityConsumption
              - energy
              - fillingLevel
              - flow
              - freeChlorine
              - gasConsumption
              - gateOpening
              - heading
              - humidity
              - light
              - location
              - milking
              - motion
              - movementActivity
              - noiseLevel
              - occupancy
              - organicMatter
              - orp
              - oxygen
              - pH
              - piezometricLevel
              - polyethylene
              - power
              - precipitation
              - pressure
              - refractiveIndex
              - salinity
              - smoke
              - soilMoisture
              - solarRadiation
              - speed
              - tds
              - temperature
              - trafficFlow
              - transparency
              - tss
              - turbidity
              - uvLampIntensity
              - uvOrganicLoad
              - volume
              - waterConsumption
              - waterLevel
              - waterPollution
              - weatherConditions
              - weight
              - windDirection
              - windSpeed
            type: string
          type: array
          x-ngsi:
            model: https://schema.org/Text
            type: Property
            uri-prefix: https://smartdatamodels.org/
    
      x-ngsi:
        uri-prefix: https://github.com/smart-data-models/dataModel.Device/blob/master/
  
    DeviceMeasurement:
      type: object
      allOf:
        - $ref: https://raw.githubusercontent.com/smart-data-models/dataModel.Device/master/DeviceMeasurement/model.yaml#/DeviceMeasurement

      x-ngsi:
        uri-prefix: https://github.com/smart-data-models/dataModel.Device/blob/master/
    
    WaterNetwork:
      type: object
      allOf:
        - $ref: https://raw.githubusercontent.com/smart-data-models/dataModel.WaterDistributionManagementEPANET/master/WaterNetwork/model.yaml#/WaterNetwork

      x-ngsi:
        uri-prefix: https://github.com/smart-data-models/dataModel.WaterDistributionManagementEPANET/blob/master/
    
    PiezometricNet:
      type: object
      allOf:
        - $ref: ./piezometricNet.yaml#/PiezometricNet
      x-ngsi:
        uri-prefix: https://raw.githubusercontent.com/mariete1223/MarMenor/main/PiezometricNet/piezometricNet.yaml#/

    Buoy:
      type: object
      allOf:
        - $ref: ./buoy.yaml#/Buoy
      x-ngsi:
        uri-prefix: https://raw.githubusercontent.com/mariete1223/MarMenor/main/Buoy/buoy.yaml#/
    Ravine:
      type: object
      allOf:
        - $ref: ./ravine.yaml#/Ravine
      x-ngsi:
        uri-prefix: https://raw.githubusercontent.com/mariete1223/MarMenor/main/Ravine/ravine.yaml#/
    PiezometricPoint:
      type: object
      allOf:
        - $ref: ./piezometricPoint.yaml#/PiezometricPoint
      x-ngsi:
        uri-prefix: https://raw.githubusercontent.com/mariete1223/MarMenor/main/PiezometricPoint/piezometricPoint.yaml#/
info: 
  description: "Model Definition for Mar Menor enviroment"
  title: Smart Devices Mar Menor Data Models
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object